Repository DontShaveTheYak/cloud-radar, pull requests merged in 2023-06, with the labels that each got.

#221 Fix bug where conditional resources were being resolved
  src/cloud_radar/cf/unit/_template.py
  tests/templates/log_bucket/log_bucket.yaml
Labels: bug, patch

#225 Fix issue with conditional outputs
  src/cloud_radar/cf/unit/_template.py
  tests/templates/log_bucket/log_bucket.yaml
Labels: bug, patch

#227 Add support for dynamic references
  README.md
  src/cloud_radar/cf/unit/_template.py
  tests/test_cf/test_unit/test_template.py
Labels: enhancement, minor

#233 Push release candidates to the real PyPi
  .github/workflows/release.yml
Labels: patch, chore

#234 add codecov config file
  codecov.yml
Labels: minor, chore

#229 Add parameter validation
  src/cloud_radar/cf/unit/_template.py
  tests/test_cf/test_unit/test_template.py
Labels: enhancement, minor

#238 allow ssm dynamic references to not include a version
  src/cloud_radar/cf/unit/_template.py
  tests/test_cf/test_unit/test_template.py
Labels: bug, patch

#247 fix rendering of resources with a condition but not Properties
  src/cloud_radar/cf/unit/_template.py
  tests/templates/log_bucket/log_bucket.yaml
Labels: bug, patch
