Repository DontShaveTheYak/cloud-radar, pull requests merged in 2025-02, with the labels that each got.

#425 docs: added myself to contributers list #423
  README.md
  pyproject.toml
Labels: documentation, patch, chore

#422 remove check for nested intrinsic functions
  src/cloud_radar/cf/unit/_template.py
  src/cloud_radar/cf/unit/functions.py
  src/cloud_radar/cf/unit/test__template.py
  tests/test_cf/test_unit/test_template.py
Labels: enhancement, minor

#427 fix(params): change error messages to include parameter names #171
  src/cloud_radar/cf/unit/_template.py
  tests/test_cf/test_unit/test_template.py
Labels: bug, patch
